import { Node, Edge } from '@xyflow/react';

export function generateSQL(nodes: Node[], edges: Edge[]): string {
  let sql = `-- Generated by DrawDB\n\n`;

  // 1. Generate Tables
  nodes.filter(n => n.type === 'table').forEach(node => {
    const data = node.data as any;
    sql += `CREATE TABLE ${data.name} (\n`;
    
    const columnDefs = data.columns.map((col: any) => {
      let def = `  ${col.name} ${col.type}`;
      if (col.is_pk) def += ` PRIMARY KEY`;
      if (col.is_ai) def += ` AUTO_INCREMENT`;
      if (!col.nullable) def += ` NOT NULL`;
      return def;
    });

    sql += columnDefs.join(',\n');
    sql += `\n) ENGINE=InnoDB;\n\n`;
  });

  // 2. Generate Foreign Keys
  edges.forEach(edge => {
    const sourceNode = nodes.find(n => n.id === edge.source);
    const targetNode = nodes.find(n => n.id === edge.target);
    
    if (sourceNode && targetNode && edge.data) {
      const sourceTable = (sourceNode.data as any).name;
      const targetTable = (targetNode.data as any).name;
      const sourceCol = edge.data.sourceColumn;
      const targetCol = edge.data.targetColumn;

      sql += `ALTER TABLE ${sourceTable}\n`;
      sql += `ADD CONSTRAINT fk_${sourceTable}_${sourceCol}\n`;
      sql += `FOREIGN KEY (${sourceCol}) REFERENCES ${targetTable}(${targetCol})\n`;
      sql += `ON DELETE CASCADE;\n\n`;
    }
  });

  return sql;
}
